language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

install: true

script:
  - go test -v -race ./...

notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: SN2hM0so3FehWvKL5a0LAPuJ4NDDAeA6VqsAPTCR1utiOSnUhdnXFREEGqL8FaLpQPMw/kHZuF4tYtXSaQnP+rOVjgmJ46wEpnMiEN7tbvfBf+lws7BiaP/Y3xYOi2ckSgkIabC7YQUQ5IYcIeyIlPXGX9BYNQ4t1t1ia1fY633zqYNbOUlUvjU82nUyU7DppZB2D1TeQLA1zzvOcgjSqDYF9xKHEi17jf7MSaBnnXi6yVuh+xvdwWg4T1rp7yJki/i0GxD/sArLORnJbuSFRvCDUFfD2PN1fPvsqOZRS2GiCeA8n/3jc8prhQxtWkFKqg4gA4W+AX8dnOi2j1MWn6WANovw6TyytNNRVxj91MTmZ2WTSedqunZWy3YLS9RB0E8zEvEZND+5KzIsOWzaq+9xIRH8iLX91B+xe52MGl0KsitjzB3BhgaJK4PKD5B6tipSDlukcdT08czLZBrlMA3p+iUfuNPsUS+rQ+IkI+TpouzEIuSfOkJloYvFeP7qDeqOH0hXSAXdAQ+ITfNjQPl8x2dwknh+uiz3RtDveEeQfEGP5Nf6W229oVEYyccMzux3//RI4Cy11of7YM79Xi7dJ2iS9tn1Ny0xUbOwuFsIa8DhlR/sQF9F8VGYSvowQOzrYhfS1sXNuiiFgyAau20YTl2B1+V9LTAc/IZy4nM=
