language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

install: true

script:
  - go test -v -race ./...

notifications:
  email: false
  slack:
    secure: k5kH+cihFy05itnMnYik6pJ4Om6JxZNIG22BUrRaGjaL/dvTSkUJrVOCW06lnO56YwtHWIJ0l71h7TXAfPlmK6E462Gw+aQyiWj/9hCe1SOBFRWVQOc9Ev3MsPJ3f8byvTgReVK6wqui6Lr/0ntfT3LhdGUQLDKnW8wGdPACbygGyrorY99ceCAhHzAKlZ0HoiWpltlGQeb0crpkvL3Wj+0owXY4i4uyOJDAjgG8OTk+0VHbaiK6AS7IGABo5pyNOBHwN1w852wR6Oscq1ncVpUArReGH7Ucq9kzo8lx0yDa+d7hsEMwHQiZhYsurL8KCM9FJbBxdtXgINCIqfuU2/mngeoSSYGVKo0NrtB1uiVgv7yDb/x93JhpcT8sFaPKyrRBPKRTDNcoApMW1M0aSc1kd9YVm3rU5CmjXCrPToWT1aG/VW7RgJ2r6BM+95GjhdlfRFPythaC3gKPGtN5Kh6hsVPtk8bG6ZR06Xb1okIaXSW9WsRRTf2S0djSdnj5KJ1mWa3mPQ1qGyvVIvVL5AWcMMeBNCtaih9oo29X6cwMP/xLcJBYJWg0uzpFP3+1Nthaee6mKGbk9vUZYSeUNHnosYblZLu+TcFQpzlkPva6y7BuHIQtQZ4/1VZXEorF0oL9lso2eZSUxD2hUImhYe6GacPpYWNRuS+Bn6pXGo0=
