language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

install: true

script:
  - go test -v -race ./...

notifications:
  email: false
  slack:
    secure: q56r1n/3UM3iMy9nKY/zUd6lxPW8cWOD6D7x3ku5una1ut8j1PqWs8K3F0Uda55TbPRa3ufWyZ15bSjxR+UZIMS1egn4f4MEp3LKiskQxyYzf3chbOEW825I9Q/iG18qFoBJNbiJDbnEUg6UzFhjV/TJ80hpaE+W4lhnnK+9aUuTMEKvfx9HeAib3OrqaAH+EmmUTUvI+UUl+5BOZdtXTZ58kGckOWHdUuS0bSUyxX6grpmOE0LXIVyOthIODFUVouFBtU4Z9KCvrHyM2BhlA/vm7txOLGvsFkRbVbflD5YAAUPzcZjuoQa3pyJ+V8uGf4uoChneLaX1skka4ICYHJAMS3Q1vkda8DUAAiOQShTUHk4/Y8sNJzXfXcVDL1d1vzEljOSfQwYgSudIecFUJKScC3Dtp3X6jNg2v1DB3zzXZcIFlkrUncvxEOkSplp3d3IB3bUBSDuxR/ktiqWgkEtkUAZG9woguNxpgmtu5fF4kvNcnPMYGg2nmzZ9fcFfZ1NJ75NHxPgBZpbQ2/aDS8+HP+gVk/fud8WcM+Hg60JWzq1SSkRWyHa4+3LmEFJcvCjYvxWymRaC2kjMUYNkVFZi3biz1v1HeCtuh7DFeaxkKKJMcH1c0M1snP0IMR1wgomptACwpiQWXAXw0dIoXjkosJxzcSiQXRzAscAE70Y=
